-- MySQL Script generated by MySQL Workbench
-- 11/06/17 15:12:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tesztkitolto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tesztkitolto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tesztkitolto` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tesztkitolto` ;

-- -----------------------------------------------------
-- Table `tesztkitolto`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `nev` VARCHAR(45) NOT NULL COMMENT '',
  `passmd5` VARCHAR(255) NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `active` TINYINT(1) NOT NULL COMMENT '',
  `guid` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`uid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesztkitolto`.`tesztek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`tesztek` (
  `tid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cim` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`tid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesztkitolto`.`tesztkerdesek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`tesztkerdesek` (
  `tkid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `kerdestxt` MEDIUMTEXT NULL COMMENT '',
  `kerdeshtml` MEDIUMTEXT NULL COMMENT '',
  `kerdesbin` MEDIUMBLOB NULL COMMENT '',
  `tipus` VARCHAR(45) NULL COMMENT '',
  `kategoria` VARCHAR(45) NULL COMMENT '',
  `nehezseg` DECIMAL(10,2) NULL COMMENT '',
  PRIMARY KEY (`tkid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesztkitolto`.`teszt_tesztkerdes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`teszt_tesztkerdes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tid` INT NOT NULL COMMENT '',
  `tkid` INT NOT NULL COMMENT '',
  `sorszam` INT NOT NULL COMMENT '',
  `helyespontszam` INT NOT NULL DEFAULT 1 COMMENT '',
  `hibaspontszam` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_teszt_tesztkerdes_tesztek1_idx` (`tid` ASC)  COMMENT '',
  INDEX `fk_teszt_tesztkerdes_tesztkerdesek1_idx` (`tkid` ASC)  COMMENT '',
  CONSTRAINT `fk_teszt_tesztkerdes_tesztek1`
    FOREIGN KEY (`tid`)
    REFERENCES `tesztkitolto`.`tesztek` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teszt_tesztkerdes_tesztkerdesek1`
    FOREIGN KEY (`tkid`)
    REFERENCES `tesztkitolto`.`tesztkerdesek` (`tkid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesztkitolto`.`kitoltesek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`kitoltesek` (
  `kid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tid` INT NOT NULL COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  `startdatum` DATETIME NOT NULL COMMENT '',
  `enddatum` DATETIME NULL COMMENT '',
  `osszpont` INT NULL COMMENT '',
  PRIMARY KEY (`kid`)  COMMENT '',
  INDEX `fk_kitoltesek_users_idx` (`uid` ASC)  COMMENT '',
  INDEX `fk_kitoltesek_tesztek1_idx` (`tid` ASC)  COMMENT '',
  CONSTRAINT `fk_kitoltesek_users`
    FOREIGN KEY (`uid`)
    REFERENCES `tesztkitolto`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kitoltesek_tesztek1`
    FOREIGN KEY (`tid`)
    REFERENCES `tesztkitolto`.`tesztek` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesztkitolto`.`kitoltesvalaszok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`kitoltesvalaszok` (
  `kvid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `kid` INT NOT NULL COMMENT '',
  `tkid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`kvid`)  COMMENT '',
  INDEX `fk_kitoltesvalaszok_kitoltesek1_idx` (`kid` ASC)  COMMENT '',
  CONSTRAINT `fk_kitoltesvalaszok_kitoltesek1`
    FOREIGN KEY (`kid`)
    REFERENCES `tesztkitolto`.`kitoltesek` (`kid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kitoltesvalaszok_tesztkerdesek1`
    FOREIGN KEY (`kvid`)
    REFERENCES `tesztkitolto`.`tesztkerdesek` (`tkid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesztkitolto`.`tesztvalaszok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesztkitolto`.`tesztvalaszok` (
  `tvid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tkid` INT NOT NULL COMMENT '',
  `sorszam` INT NOT NULL COMMENT '',
  `valasztxt` MEDIUMTEXT NULL COMMENT '',
  `valaszhtml` MEDIUMTEXT NULL COMMENT '',
  `valaszbin` MEDIUMBLOB NULL COMMENT '',
  `helyese` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`tvid`)  COMMENT '',
  INDEX `fk_tesztvalaszok_tesztkerdesek1_idx` (`tkid` ASC)  COMMENT '',
  CONSTRAINT `fk_tesztvalaszok_tesztkerdesek1`
    FOREIGN KEY (`tkid`)
    REFERENCES `tesztkitolto`.`tesztkerdesek` (`tkid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
